## Example

Create an array of shape(3,4). Find the mean and median of array row wise and column wise. Print the array value if each cell value is greater than 5 other wise print 0.

In [34]:
import numpy as np

In [35]:
arr = np.arange(12).reshape(3,4)

In [36]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
# column wise
np.mean(arr,axis=0)

array([4., 5., 6., 7.])

In [38]:
# row wise
np.mean(arr,axis=1)

array([1.5, 5.5, 9.5])

In [39]:
# column wise
np.median(arr,axis=0)

array([4., 5., 6., 7.])

In [40]:
# row wise
np.median(arr,axis=1)

array([1.5, 5.5, 9.5])

In [41]:
index = arr>5
index

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [42]:
arr[arr<5]=0

In [43]:
arr

array([[ 0,  0,  0,  0],
       [ 0,  5,  6,  7],
       [ 8,  9, 10, 11]])