In [50]:
import pandas as pd


In [51]:
df = pd.read_pickle('../data/georgia-history.pkl')

In [52]:
df.head()

death  deathIncrease  hospitalized  hospitalizedCumulative  \
date                                                                       
2021-03-07  17906.0              1       56797.0                 56797.0   
2021-03-06  17905.0             90       56762.0                 56762.0   
2021-03-05  17815.0             65       56627.0                 56627.0   
2021-03-04  17750.0            125       56512.0                 56512.0   
2021-03-03  17625.0            145       56369.0                 56369.0   

            hospitalizedCurrently  hospitalizedIncrease  inIcuCumulative  \
date                                                                       
2021-03-07                 2008.0                    35           9263.0   
2021-03-06                 2071.0                   135           9260.0   
2021-03-05                 2099.0                   115           9236.0   
2021-03-04                 2191.0                   143           9221.0   
2021-03-03                 2299.0                   118           9186.0   

            positive  positiveCasesViral  positiveIncrease  positiveTestsViral  
date                                                                            
2021-03-07   1023487            828336.0              1709              803515  
2021-03-06   1021778            827397.0              2269              802411  
2021-03-05   1019509            826117.0              2081              801097  
2021-03-04   1017428            824804.0              2886              799666  
2021-03-03   1014542            823008.0              2735              798161

In [53]:
df.isna().sum()

death                      0
deathIncrease              0
hospitalized              12
hospitalizedCumulative    12
hospitalizedCurrently     49
hospitalizedIncrease       0
inIcuCumulative           45
positive                   0
positiveCasesViral        47
positiveIncrease           0
positiveTestsViral         0
dtype: int64

In [54]:
df = df[['death','deathIncrease','hospitalizedIncrease','positive','positiveIncrease','positiveTestsViral']]

In [55]:
df.head()

death  deathIncrease  hospitalizedIncrease  positive  \
date                                                                 
2021-03-07  17906.0              1                    35   1023487   
2021-03-06  17905.0             90                   135   1021778   
2021-03-05  17815.0             65                   115   1019509   
2021-03-04  17750.0            125                   143   1017428   
2021-03-03  17625.0            145                   118   1014542   

            positiveIncrease  positiveTestsViral  
date                                              
2021-03-07              1709              803515  
2021-03-06              2269              802411  
2021-03-05              2081              801097  
2021-03-04              2886              799666  
2021-03-03              2735              798161

In [56]:
df.isna().sum()

death                   0
deathIncrease           0
hospitalizedIncrease    0
positive                0
positiveIncrease        0
positiveTestsViral      0
dtype: int64

## Numpy

In [57]:
# Convert data to numpy array

# Arrays are important because they enable you to express batch operations on data without writing any for loops. This is usually called vectorization. 
import numpy as np
array = df.to_numpy()

In [58]:
# Find the maximum values along columns
array.max(axis=0)


array([1.790600e+04, 4.800000e+02, 6.110000e+02, 1.023487e+06,
       3.160500e+04, 8.035150e+05])

In [59]:
# Find the minimum values along columns
array.min(axis=0)

array([ 1.,  0.,  0., 42., 11., 32.])

In [60]:
# Find the mean values along columns

array.mean(axis=0)

array([6.52556111e+03, 4.97388889e+01, 1.57769444e+02, 3.43052811e+05,
       2.84293333e+03, 2.87568761e+05])

In [61]:
# Find the median values along columns

np.median(array,axis=0)

array([6.099000e+03, 3.600000e+01, 1.315000e+02, 2.863185e+05,
       2.068000e+03, 2.621070e+05])

In [62]:
array.shape

(360, 6)

In [63]:
# Transposing array
array_transpose = array.T
array_transpose.shape

(6, 360)

In [64]:
# To get the first row
array[0]

array([1.790600e+04, 1.000000e+00, 3.500000e+01, 1.023487e+06,
       1.709000e+03, 8.035150e+05])

In [65]:
# Accessing all rows and first column

array[:,1]

array([  1.,  90.,  65., 125., 145., 104.,  81.,   1.,  75.,  20., 135.,
       137.,  92.,  91.,   2., 132., 207., 130.,  99., 246.,  57.,  21.,
       142., 195.,  92., 120., 171.,  38.,   2., 232., 102., 169., 137.,
       208.,  44.,   2., 210., 159., 184., 161., 179.,  53.,   4., 186.,
       171., 111., 196., 222.,  64.,   5., 153., 163., 172., 141., 187.,
        17.,   1., 143.,  84.,  65.,  93., 101.,   7.,   4.,   2.,  24.,
        88.,  67.,  83.,   7.,   4.,  54.,  49.,  63.,  56.,  64.,  16.,
         2.,  49.,  38.,  66.,  68.,  56.,  28.,   1.,  44.,  56.,  54.,
        48.,  22.,  45.,  13.,  68.,  77.,  81.,  52.,  63.,  10.,  18.,
        44.,  44.,  39.,  76.,   6.,  17.,  19.,  37.,  40.,  37.,  57.,
        41.,  10.,   1.,  51.,  24.,  75.,  76.,  53.,  29.,   1.,  39.,
        30.,  56.,  43., 480.,  18.,   2.,  24.,  32.,  47.,  32.,  17.,
        18.,   1.,  42.,  37.,  25.,  30.,  17.,  19.,  31.,  51.,  64.,
        22.,  16.,  25.,  13.,  23.,  45.,  54.,  3

In [66]:
array_transpose

array([[1.790600e+04, 1.790500e+04, 1.781500e+04, ..., 1.000000e+00,
        1.000000e+00, 1.000000e+00],
       [1.000000e+00, 9.000000e+01, 6.500000e+01, ..., 0.000000e+00,
        0.000000e+00, 1.000000e+00],
       [3.500000e+01, 1.350000e+02, 1.150000e+02, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [1.023487e+06, 1.021778e+06, 1.019509e+06, ..., 9.900000e+01,
        6.600000e+01, 4.200000e+01],
       [1.709000e+03, 2.269000e+03, 2.081000e+03, ..., 3.300000e+01,
        2.400000e+01, 1.100000e+01],
       [8.035150e+05, 8.024110e+05, 8.010970e+05, ..., 6.800000e+01,
        4.100000e+01, 3.200000e+01]])

In [67]:
# Let's find the 
array[:,0]-array[:,1]

array([1.7905e+04, 1.7815e+04, 1.7750e+04, 1.7625e+04, 1.7480e+04,
       1.7376e+04, 1.7295e+04, 1.7294e+04, 1.7219e+04, 1.7199e+04,
       1.7064e+04, 1.6927e+04, 1.6835e+04, 1.6744e+04, 1.6742e+04,
       1.6610e+04, 1.6403e+04, 1.6273e+04, 1.6174e+04, 1.5928e+04,
       1.5871e+04, 1.5850e+04, 1.5708e+04, 1.5513e+04, 1.5421e+04,
       1.5301e+04, 1.5130e+04, 1.5092e+04, 1.5090e+04, 1.4858e+04,
       1.4756e+04, 1.4587e+04, 1.4450e+04, 1.4242e+04, 1.4198e+04,
       1.4196e+04, 1.3986e+04, 1.3827e+04, 1.3643e+04, 1.3482e+04,
       1.3303e+04, 1.3250e+04, 1.3246e+04, 1.3060e+04, 1.2889e+04,
       1.2778e+04, 1.2582e+04, 1.2360e+04, 1.2296e+04, 1.2291e+04,
       1.2138e+04, 1.1975e+04, 1.1803e+04, 1.1662e+04, 1.1475e+04,
       1.1458e+04, 1.1457e+04, 1.1314e+04, 1.1230e+04, 1.1165e+04,
       1.1072e+04, 1.0971e+04, 1.0964e+04, 1.0960e+04, 1.0958e+04,
       1.0934e+04, 1.0846e+04, 1.0779e+04, 1.0696e+04, 1.0689e+04,
       1.0685e+04, 1.0631e+04, 1.0582e+04, 1.0519e+04, 1.0463e

In [68]:
def my_func(a):
    """Average first and last element of a 1-D array"""
    return (a[0] + a[-1]) * 0.5

In [69]:
np.apply_along_axis(my_func, 0, array)

array([8.953500e+03, 1.000000e+00, 1.750000e+01, 5.117645e+05,
       8.600000e+02, 4.017735e+05])

In [70]:
# Sum over columns.
np.apply_over_axes(np.sum, array, axes=0)

array([[2.34920200e+06, 1.79060000e+04, 5.67970000e+04, 1.23499012e+08,
        1.02345600e+06, 1.03524754e+08]])