# Pandas

Pandas provide a high level data structure with convenient functions to read and parse data. It is built on top of numpy and can interact with multiple file formats 

To install panda 

!pip install pandas


In [1]:
import pandas as pd
import numpy as np

Two Data Types

* Series - One dimensional labeled array. Can hold data of any type.
* Dataframe - a two dimensional labeled datastructure that can hold data of any type. However, you will see performance decreases if you use data types that aren’t handled well by C.

## 1. Series
First, lets make a pandas series from a numpy array.

In [2]:
arr = np.random.rand(3)

In [3]:
arr

array([0.81290389, 0.12252748, 0.88448147])

In [4]:
arr_series = pd.Series(arr)

Now we have a series object, which you can easily display in a notebook by typing its name:

In [5]:
arr_series

0    0.812904
1    0.122527
2    0.884481
dtype: float64

## 2. Dataframe
Now lets create a pandas dataframe in a similar way. The majority of data structures you will make will likely be dataframes.


In [6]:
arr_1 = np.random.rand(3,4)

In [7]:
arr_1

array([[0.58961565, 0.74778079, 0.63589935, 0.74962347],
       [0.91742817, 0.38101643, 0.12718552, 0.5571277 ],
       [0.64671335, 0.63386282, 0.26188873, 0.78521223]])

In [8]:
arr_1_dataframe = pd.DataFrame(arr_1)

We now have our dataframe, lets display it:


In [9]:
arr_1_dataframe

0         1         2         3
0  0.589616  0.747781  0.635899  0.749623
1  0.917428  0.381016  0.127186  0.557128
2  0.646713  0.633863  0.261889  0.785212

There are a variety of built in variables that dataframes posses, for the sake of explanation, we will make a new dataframe using the original one-dimensional numpy array:


In [10]:
arr_dataframe = pd.DataFrame(arr)

In [11]:
arr_dataframe

0
0  0.812904
1  0.122527
2  0.884481

df.dtypes refers to the datatypes of all fields in the dataframe:


In [12]:
arr_dataframe.dtypes

0    float64
dtype: object

df.index refers to the labels/rows of each datapoint:

In [13]:
arr_dataframe.index

RangeIndex(start=0, stop=3, step=1)

df.columns refers to the fields of the dataframe:

In [14]:
arr_dataframe.columns

RangeIndex(start=0, stop=1, step=1)

Note that we can change these variables:

In [15]:
arr_dataframe.columns = ["Value"]

In [16]:
arr_dataframe

Value
0  0.812904
1  0.122527
2  0.884481

df.values refers to the values at each point (it is rare that we actually use this, but it is good to know):

In [17]:
arr_dataframe.values

array([[0.81290389],
       [0.12252748],
       [0.88448147]])

df.shape refers to the dimensionality of the dataframe:

In [18]:
arr_dataframe.shape

(3, 1)